version: 0.2

phases:
  build:
    commands:
      - echo "Preparing files for deployment..."
      - mkdir -p output
      - cp -r DevOps6/wwwroot/* output/

artifacts:
  files:
    - '**/*'
  base-directory: output
